### ISSUE TITLE
Custom translation load strategy for locale routing

### ISSUE THREAD

**Issue by danielanteloagra** [symfony-cmf/RoutingBundle#282]
How can I override the default locale routing strategy to specify how it should find translated content for local enabled routes?

To put it into context, my phpcr/jackrabbit structure consists of a standalone versioned master document that is  copied to create frozen nodes used as references for external translation. Translations are then independent versioned documents.

```yml
ROOT:
    mstr:
        a-doc
    ref:
        a-doc:
           1.0
           1.7
    locale:
        en-UK:
           a-doc
        es-ES:
           a-doc
```

So when I create a route that is linked to /mstr/a-doc and enable locale patterning. I would like to be able to override how it finds the translation so that it gets the relevant document from /locale/{_locale}/a-doc

[Stack overflow reference](http://stackoverflow.com/questions/27865720/cmfroutingbundle-phpcr-odm-custom-translation-strategy)
