### ISSUE TITLE
Cant Configure my RoutingBundle ParameterNotFoundException 

### ISSUE THREAD

**Issue by houss2040** [symfony-cmf/RoutingBundle#305]
I work with MongoDB db, this is my configuration file  

```
cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        persistence:
            phpcr:
                enabled: true
```  

And this is my composer.json

```
(...)
"symfony-cmf/symfony-cmf": "1.2.0",
 "jackalope/jackalope-doctrine-dbal": "1.2.2"
```

I get this exception : 

```
ParameterNotFoundException: You have requested a non-existent parameter "None of the managerParameters resulted in a valid name".
```
